version: '3'

services:
  api:
    build:
      dockerfile: .
      context: ./api
    image: ds-image
    container_name: ds-api
    ports:
      - "3333:3333"
    networks:
      - ds-network
    volumes:
      - ./api:/usr/src/api
    depends_on:
      - mongodb
  mongodb:
    container_name: food-order-mongo
    image: mongo:latest
    restart: unless-stopped
    
    ports:
      - 27017:27017
    volumes:
      - db:/data/db
    networks:
      - ds-network
  app:
    build:
      dockerfile: .
      context: ./client
    image: ds-client-image
    container_name: ds-client-web
    ports:
      - '3000:3000'
    volumes:
      - ./client:/usr/src/app
    networks:
      - ds-network

volumes:
  db:

networks:
  ds-network:
    driver: bridge



    