version: '3'

services:
  api:
    build:
      dockerfile: .
      context: ./api
    image: ds-image
    container_name: ds-api
    ports:
      - "3333:3333"
    networks:
      - ds-network
    volumes:
      - ./api:/usr/src/api
    depends_on:
      - postgres
  postgres:
    image: postgres
    container_name: ds-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=ds
      - POSTGRES_USER=ds
      - POSTGRES_PASSWORD=ds
    networks:
      - ds-network
  app:
    build:
      dockerfile: .
      context: ./client
    image: ds-client-image
    container_name: ds-client-web
    ports:
      - '3000:3000'
    volumes:
      - ./client:/usr/src/app
    networks:
      - ds-network
networks:
  ds-network:
    driver: bridge



    